### ISSUE TITLE
Compiling with TDM-GCC

### ISSUE THREAD

**Issue by OscarL** [lilkui/runasti#2]
In order to compile cleanly with TDM-GCC (at least with version 9.2), one needs to add `#include <locale>` to `program.cpp`.

Also, and kind of off topic, but running `runasti.exe` from an unprivileged cmd.exe, outputs `std::exception`. Being new to this (or just dumb :-D), it took me a while to figure out I should run it with Admin privileges. Not sure why the exception text is so unspecific in this case.

**Comment by lilkui** [comment]
This tool starts a TrustedInstaller service and duplicates its token. Starting services requires admin priviledge. If run without admin privilege, a message that reads "OpenService failed: 5" should be displayed. (5 is ERROR_ACCESS_DENIED.)
BTW, this tool is just a toy :-D

**Comment by OscarL** [comment]
> If run without admin privilege, a message that reads "OpenService failed: 5" should be displayed. (5 is ERROR_ACCESS_DENIED.)

Well... that does not seems to be the case when compiled with TDM-GCC-9.2 (I don't have/use Visual Studio).

I'll see if using the latest version of TDM-GCC (and newer MinGW-W64) helps in that regard. In any case... I guess that adding that `#include <locale>` would still be required (for the `std::wstring_convert()` function call).

In any case, I just wanted to document this, either for you to include, or as a reference for my future self :-)

> BTW, this tool is just a toy :-D

You might consider it a toy, but hey... it worked for me when I needed it!

I found it much more appealing than similar tools written on AutoIT or something like that :-D

So... thanks for your work, much appreciated!!!

**Comment by lilkui** [comment]
FYI, you may get rid of std::string and just use const char* instead.
I was just experimenting with std::string at that time 😂
